port: 8080
# Site settings
title: William.Kamovit.ch
email: wjkamovitch@gmail.com
description: "The personal blog for William Kamovitch"
baseurl: ""
url: "https://william.kamovit.ch"
twitter_username: wkamovitch
github_username:  ibexian

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
gems: [jekyll-paginate]
exclude: ["node_modules","package.json","README.md", "Gemfile", "Gemfile.lock", "webpack.config.js", "Makefile"]
